=== PPWA/textsearchapp/BreakingNews/iisys-server/schemas/RSSFeeds.xsd
<?xml version="1.0" encoding="ASCII"?>

<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.iisys.de/mmis/rssapp"
  xmlns="http://www.iisys.de/mmis/rssapp"
  elementFormDefault="qualified">

  <xsd:element name="sites">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="address" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="ttl" type="xsd:positiveInteger"/>
            <xsd:attribute name="topic" type="xsd:string"/>
            <xsd:attribute name="country" type="xsd:string"/>
            <xsd:attribute name="language" type="xsd:language"/>
            <xsd:attribute name="link" type="xsd:anyURI"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType> 
  </xsd:element>
</xsd:schema>

=== PPWA/textsearchapp/BreakingNews/iisys-server/sources/ZeitOnline.xml
<?xml version="1.0" encoding="ASCII"?>

<sites
  xmlns="http://www.iisys.de/mmis/rssapp"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.iisys.de/mmis/rssapp RSSFeeds.xsd">

  <address ttl="2" topic="business" country="germany" language="de" link="http://newsfeed.zeit.de/wirtschaft/index"/>
  <address ttl="2" topic="career" country="germany" language="de" link="http://newsfeed.zeit.de/karriere/index"/>
  <address ttl="2" topic="computer" country="germany" language="de" link="http://newsfeed.zeit.de/digital/index"/>
  <address ttl="2" topic="culture" country="germany" language="de" link="http://newsfeed.zeit.de/kultur/index"/>
  <address ttl="2" topic="lifestyle" country="germany" language="de" link="http://newsfeed.zeit.de/lebensart/index"/>
  <address ttl="2" topic="mobility" country="germany" language="de" link="http://newsfeed.zeit.de/auto/index"/>
  <address ttl="2" topic="opinion" country="germany" language="de" link="http://newsfeed.zeit.de/meinung/index"/>
  <address ttl="2" topic="politics" country="germany" language="de" link="http://newsfeed.zeit.de/politik/index"/>
  <address ttl="2" topic="science" country="germany" language="de" link="http://newsfeed.zeit.de/wissen/index"/>
  <address ttl="2" topic="society" country="germany" language="de" link="http://newsfeed.zeit.de/gesellschaft/index"/>
  <address ttl="2" topic="sport" country="germany" language="de" link="http://newsfeed.zeit.de/sport/index"/>
  <address ttl="2" topic="study" country="germany" language="de" link="http://newsfeed.zeit.de/studium/index"/>
  <address ttl="2" topic="travel" country="germany" language="de" link="http://newsfeed.zeit.de/reisen/index"/>
</sites>

=== PPWA/textsearchapp/BreakingNews/iisys-server/sources/FAZ.xml
<?xml version="1.0" encoding="ASCII"?>

<sites
  xmlns="http://www.iisys.de/mmis/rssapp"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.iisys.de/mmis/rssapp RSSFeeds.xsd">

  <address ttl="2" topic="career" country="germany" language="de" link="http://www.faz.net/rss/aktuell/beruf-chance/"/>
  <address ttl="2" topic="culture" country="germany" language="de" link="http://www.faz.net/rss/aktuell/feuilleton/"/>
  <address ttl="2" topic="finance" country="germany" language="de" link="http://www.faz.net/rss/aktuell/finanzen/"/>
  <address ttl="2" topic="society" country="germany" language="de" link="http://www.faz.net/rss/aktuell/gesellschaft/"/>
  <address ttl="2" topic="politics" country="germany" language="de" link="http://www.faz.net/rss/aktuell/politik/"/>
  <address ttl="2" topic="travel" country="germany" language="de" link="http://www.faz.net/rss/aktuell/reise/"/>
  <address ttl="2" topic="sport" country="germany" language="de" link="http://www.faz.net/rss/aktuell/sport/"/>
  <address ttl="2" topic="technology" country="germany" language="de" link="http://www.faz.net/rss/aktuell/technik-motor/"/>
  <address ttl="2" topic="business" country="germany" language="de" link="http://www.faz.net/rss/aktuell/wirtschaft/"/>
  <address ttl="2" topic="science" country="germany" language="de" link="http://www.faz.net/rss/aktuell/wissen/"/>
</sites>
